apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-w5hn
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0064-tenant/tkrw-pr712-0075-0064-app/devfile-sample-w5hn@sha256:d313321fedcd4f78594fc7d04787fb306031589c9ae36db8536409f3a9b90e92
        name: my-nodejs
        resources: {}
status: {}
